#!/usr/bin/env python3
"""
为常用图标添加简化别名
"""
import json
import sys

# 常用简化名称到完整名称的映射
COMMON_ALIASES = {
    "Back": "ChromeBack",
    "Forward": "Forward",
    "Search": "Search",
    "Home": "Home",
    "Settings": "Settings",
    "Close": "ChromeClose",
    "Maximize": "ChromeMaximize",
    "Minimize": "ChromeMinimize",
    "Add": "Add",
    "Remove": "Remove",
    "Delete": "Delete",
    "Edit": "Edit",
    "Save": "Save",
    "Cancel": "Cancel",
    "OK": "Accept",
    "Yes": "Accept",
    "No": "Cancel",
    "Refresh": "Refresh",
    "Copy": "Copy",
    "Cut": "Cut",
    "Paste": "Paste",
    "Undo": "Undo",
    "Redo": "Redo",
    "ZoomIn": "ZoomIn",
    "ZoomOut": "ZoomOut",
    "Up": "Up",
    "Down": "Down",
    "Left": "ChevronLeft",
    "Right": "ChevronRight",
    "Play": "Play",
    "Pause": "Pause",
    "Stop": "Stop",
    "Help": "Help",
    "Print": "Print",
    "PrintPreview": "Print",
    "Open": "FolderOpen",
    "New": "Add",
    "Folder": "Folder",
    "File": "Document",
    "Contact": "Contact",
    "Calendar": "Calendar",
    "Mail": "Mail",
    "Phone": "Phone",
    "Camera": "Camera",
    "Video": "Video",
    "Music": "Audio",
    "Picture": "Picture",
    "Lock": "Lock",
    "Unlock": "Unlock",
    "Check": "CheckMark",
    "Checkbox": "Checkbox",
    "Radio": "RadioBullet",
    "Switch": "Switch",
    "Slider": "SliderThumb",
    "Progress": "ProgressRingDots",
    "Link": "Link",
    "Share": "Share",
    "Pin": "Pin",
    "Unpin": "Unpin",
    "Favorite": "FavoriteStar",
    "Like": "Like",
    "Dislike": "Dislike",
    "Flag": "Flag",
    "Tag": "Tag",
    "Label": "Label",
    "Sort": "Sort",
    "Filter": "Filter",
    "Group": "Group",
    "Ungroup": "Ungroup",
    "AlignLeft": "AlignLeft",
    "AlignCenter": "AlignCenter",
    "AlignRight": "AlignRight",
    "Bold": "Bold",
    "Italic": "Italic",
    "Underline": "Underline",
    "Font": "Font",
    "Color": "Color",
    "Highlight": "Highlight",
    "View": "View",
    "FullScreen": "FullScreen",
    "Picture": "Photo",
    "Code": "Code",
    "Database": "Database",
    "Cloud": "Cloud",
    "Download": "Download",
    "Upload": "Upload",
    "Sync": "Sync",
    "Connect": "Connect",
    "Disconnect": "Disconnect",
    "Bluetooth": "Bluetooth",
    "Wifi": "Wifi",
    "Ethernet": "Ethernet",
    "VPN": "VPN",
    "Battery": "BatteryUnknown",
    "Volume": "Volume",
    "Brightness": "Brightness",
    "Mute": "Mute",
    "Microphone": "Microphone",
    "Camera": "Camera",
    "Location": "Location",
    "Map": "MapPin",
    "Navigate": "Directions",
    "Car": "Car",
    "Bus": "Bus",
    "Train": "Train",
    "Walk": "Walk",
    "Bike": "Ferry",
    "Airplane": "Airplane",
    "Hotel": "BuildingEnergy",
    "Restaurant": "Cafe",
    "Shopping": "ShoppingCart",
    "Cart": "ShoppingCart",
    "Wallet": "PaymentCard",
    "Bank": "Bank",
    "Credit": "PaymentCard",
    "Debit": "PaymentCard",
    "ATM": "Bank",
    "Money": "Currency",
    "Dollar": "Currency",
    "Euro": "Currency",
    "Pound": "Currency",
    "Yen": "Currency",
    "Calculator": "Calculator",
    "Clock": "Clock",
    "Timer": "Stopwatch",
    "Alarm": "Clock",
    "Watch": "Clock",
    "Hourglass": "Clock",
    "Calendar": "Calendar",
    "Schedule": "Calendar",
    "Event": "Event12",
    "Reminder": "Reminder",
    "Task": "TaskView",
    "Todo": "TaskView",
    "Note": "Memo",
    "Memo": "Memo",
    "Document": "Document",
    "File": "Document",
    "Page": "Page",
    "Report": "ReportDocument",
    "Certificate": "Certificate",
    "Award": "Award",
    "Medal": "Award",
    "Trophy": "Award",
    "Star": "FavoriteStar",
    "Heart": "Heart",
    "Diamond": "Diamond",
    "Club": "Club",
    "Spade": "Spade",
    "Tool": "Wrench",
    "Settings": "Settings",
    "Options": "Settings",
    "Preferences": "Personalize",
    "Configure": "Settings",
    "Customize": "Personalize",
    "Admin": "Admin",
    "Manage": "Manage",
    "Control": "Control",
    "Dashboard": "ViewDashboard",
    "Monitor": "StatusCircle",
    "Status": "StatusCircle",
    "Info": "Info",
    "Warning": "Warning",
    "Error": "Error",
    "Critical": "ErrorBadge",
    "Success": "CircleFill",
    "Failure": "ErrorBadge",
    "Question": "StatusCircleQuestionMark",
    "Exclamation": "StatusExclamationCircle7",
    "Tip": "Info",
    "Hint": "Info2",
    "Suggestion": "Lightbulb",
    "Idea": "Lightbulb",
    "Notification": "MailBadge12",
    "Alert": "AlertUrgent",
    "Message": "Message",
    "Chat": "ChatBubbles",
    "Comment": "Comment",
    "Review": "Comment",
    "Feedback": "Feedback",
    "Rating": "Rating",
    "Vote": "Like",
    "Poll": "Poll",
    "Survey": "Survey",
    "Form": "Form",
    "Application": "GenericApp",
    "App": "GenericApp",
    "Program": "GenericApp",
    "Software": "GenericApp",
    "System": "System",
    "Device": "Devices",
    "Hardware": "Devices",
    "Peripheral": "Devices",
    "Accessories": "Devices",
    "Network": "Network",
    "Internet": "Globe",
    "Web": "Globe",
    "Online": "StatusConnected",
    "Offline": "NetworkOffline",
    "Available": "StatusConnected",
    "Busy": "Blocked",
    "Away": "Away",
    "Idle": "Idle",
    "Invisible": "Hide",
    "AppearOffline": "NetworkOffline",
    "User": "Contact",
    "Profile": "Contact",
    "Account": "Accounts",
    "Login": "Lock",
    "Logout": "SignOut",
    "SignIn": "Lock",
    "SignOut": "SignOut",
    "Register": "AddFriend",
    "Subscribe": "SubscriptionAdd",
    "Unsubscribe": "Remove",
    "Follow": "AddFriend",
    "Unfollow": "Remove",
    "Block": "BlockContact",
    "Unblock": "Unfavorite",
    "Mute": "Mute",
    "Unmute": "Volume",
    "Ignore": "Blocked",
    "Report": "ReportHacked",
    "Spam": "ReportHacked",
    "Archive": "ZipFolder",
    "Unarchive": "ZipFolder",
    "Compress": "ZipFolder",
    "Extract": "ZipFolder",
    "Zip": "ZipFolder",
    "Unzip": "ZipFolder",
    "RAR": "ZipFolder",
    "TAR": "ZipFolder",
    "GZIP": "ZipFolder",
    "SevenZip": "ZipFolder",
    "Encrypt": "Lock",
    "Decrypt": "Unlock",
    "Secure": "Shield",
    "Protect": "Shield",
    "Backup": "SaveLocal",
    "Restore": "UpdateRestore",
    "Recover": "UpdateRestore",
    "Repair": "Repair",
    "Fix": "Repair",
    "Maintain": "Repair",
    "Update": "UpdateRestore",
    "Upgrade": "UpdateRestore",
    "Install": "SaveLocal",
    "Uninstall": "Uninstall",
    "Remove": "Remove",
    "Delete": "Delete",
    "Clear": "Clear",
    "Reset": "ResetDevice",
    "Reboot": "RestartUpdate",
    "Shutdown": "PowerButton",
    "Power": "PowerButton",
    "Sleep": "PowerButton",
    "Hibernate": "PowerButton",
    "Restart": "RestartUpdate",
    "LogOff": "SignOut",
    "LockScreen": "LockscreenDesktop",
    "ScreenSaver": "LockscreenDesktop",
    "Wallpaper": "Personalize",
    "Theme": "Personalize",
    "Background": "BackgroundToggle",
    "Screensaver": "LockscreenDesktop",
}

def add_aliases_to_metadata(metadata_path, output_path):
    """添加常用图标别名到元数据"""
    with open(metadata_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # 创建现有图标的映射
    existing_icons = {icon['name'].upper(): icon for icon in data['icons']}

    # 添加别名
    added_count = 0
    for simple_name, full_name in COMMON_ALIASES.items():
        full_upper = full_name.upper()

        # 如果完整名称存在，且简化名称不存在
        if full_upper in existing_icons:
            simple_upper = simple_name.upper()

            # 检查是否已经存在简化名称
            if simple_upper not in existing_icons:
                # 复制完整图标并添加为别名
                original_icon = existing_icons[full_upper]
                alias_icon = original_icon.copy()

                # 更新名称
                alias_icon['name'] = simple_name
                alias_icon['enum_name'] = simple_name
                if 'i18n' in alias_icon:
                    alias_icon['i18n']['en'] = simple_name
                    # 简化中文翻译
                    alias_icon['i18n']['zh'] = simple_name

                # 添加别名标记
                alias_icon['alias_of'] = full_name

                # 添加到图标列表
                data['icons'].append(alias_icon)
                added_count += 1
                print(f"Added alias: {simple_name} -> {full_name}")

    # 保存更新后的元数据
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nAdded {added_count} aliases")
    print(f"Total icons: {len(data['icons'])}")
    return added_count

if __name__ == '__main__':
    metadata_path = 'src/UI/Lemoo.UI/Models/Icons/IconMetadata.json'
    output_path = 'src/UI/Lemoo.UI/Models/Icons/IconMetadata.json'

    add_aliases_to_metadata(metadata_path, output_path)
